# Generated by Django 4.2.2 on 2023-06-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_usuario_id_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
